apiVersion: v1
kind: Service
metadata:
  name: hello-nest-service
spec:
  selector:
    app: hello-nest   # el mismo mecanismo de labels/selector que ya vimos
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
